global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker-metrics"
    static_configs:
      - targets: ["localhost:9090"]  

  - job_name: "xgboost-api"
    static_configs:
      - targets: ["13.38.70.26:5001"]  
